// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC01KeyNumberTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC01KeyNumber() {
    driver.Navigate().GoToUrl("https://the-internet.herokuapp.com/inputs");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.CssSelector("input")).SendKeys("1");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("2");
    driver.FindElement(By.CssSelector("input")).Click();
    {
      var element = driver.FindElement(By.CssSelector("input"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector("input")).SendKeys("3");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("4");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("5");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("6");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("7");
    driver.FindElement(By.CssSelector("input")).Click();
    {
      var element = driver.FindElement(By.CssSelector("input"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector("input")).SendKeys("8");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("9");
    driver.FindElement(By.CssSelector("input")).Click();
    {
      var element = driver.FindElement(By.CssSelector("input"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector("input")).SendKeys("10");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("11");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("12");
    driver.FindElement(By.CssSelector("input")).Click();
    {
      var element = driver.FindElement(By.CssSelector("input"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector("input")).SendKeys("13");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("14");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("15");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("16");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("17");
    driver.FindElement(By.CssSelector("input")).Click();
    driver.FindElement(By.CssSelector("input")).SendKeys("18");
    driver.FindElement(By.CssSelector("input")).Click();
    {
      string value = driver.FindElement(By.CssSelector("input")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("18"));
    }
  }
}
