// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC01Mua1SPVaThanhToanTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC01Mua1SPVaThanhToan() {
    driver.Navigate().GoToUrl("https://magento.softwaretestingboard.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.CssSelector(".swatch-opt-1812 #option-label-size-143-item-168")).Click();
    driver.FindElement(By.Id("option-label-color-93-item-59")).Click();
    driver.FindElement(By.CssSelector(".product-item:nth-child(2) .actions-primary span")).Click();
    driver.FindElement(By.CssSelector(".showcart")).Click();
    driver.FindElement(By.Id("top-cart-btn-checkout")).Click();
    driver.FindElement(By.Id("customer-email")).Click();
    driver.FindElement(By.Id("customer-email")).SendKeys("thaotran@gmail.com");
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div/div/input")).SendKeys("Thao");
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[2]/div/input")).SendKeys("Tran");
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[3]/div/input")).SendKeys("Thao");
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/fieldset/div/div/div/input")).SendKeys("Aibiet");
    driver.FindElement(By.CssSelector(".street > .control")).Click();
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/fieldset/div/div[2]/div/input")).SendKeys("12");
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/fieldset/div/div[3]/div/input")).SendKeys("12");
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[4]/div/input")).SendKeys("Tp.HCM");
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[5]/div/select")).Click();
    {
      var dropdown = driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[5]/div/select"));
      dropdown.FindElement(By.XPath("//option[. = 'South Carolina']")).Click();
    }
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[7]/div/input")).Click();
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[7]/div/input")).SendKeys("23142");
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[8]/div/select")).Click();
    {
      var dropdown = driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[8]/div/select"));
      dropdown.FindElement(By.XPath("//option[. = 'Vietnam']")).Click();
    }
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[9]/div/input")).Click();
    driver.FindElement(By.XPath("//div[@id=\'shipping-new-address-form\']/div[9]/div/input")).SendKeys("08953453");
    driver.FindElement(By.CssSelector(".button > span")).Click();
    driver.FindElement(By.CssSelector(".button")).Click();
    driver.FindElement(By.CssSelector("#block-discount-heading > span")).Click();
    driver.FindElement(By.CssSelector(".checkout > span")).Click();
    driver.FindElement(By.CssSelector(".page-title-wrapper")).Click();
    var elements = driver.FindElements(By.CssSelector(".base"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector("#registration > div:nth-child(3)")).Click();
    var elements = driver.FindElements(By.CssSelector(".continue > span"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.LinkText("Continue Shopping")).Click();
  }
}
