// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC01KeyPressTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC01KeyPress() {
    driver.Navigate().GoToUrl("https://the-internet.herokuapp.com/key_presses");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    {
      WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(30));
      wait.Until(driver => driver.FindElement(By.Id("result")).Text == "You entered: T");
    }
  }
}
