// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC023DangNhapTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC023DangNhap() {
    driver.Navigate().GoToUrl("https://id.zing.vn/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Id("login_account")).Click();
    driver.FindElement(By.CssSelector(".zidbody")).Click();
    driver.FindElement(By.Id("login_account")).SendKeys("thao09345");
    driver.FindElement(By.Id("login_pwd")).Click();
    driver.FindElement(By.Id("login_pwd")).SendKeys("Hthao12345@@");
    driver.FindElement(By.Id("login_pwd")).SendKeys(Keys.Enter);
    Assert.That(driver.FindElement(By.CssSelector("#login_error .tipcontent")).Text, Is.EqualTo("Tài khoản hoặc mật khẩu không đúng"));
  }
}
