// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC02DangNhapTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC02DangNhap() {
    driver.Navigate().GoToUrl("https://id.zing.vn/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Id("login_account")).Click();
    driver.FindElement(By.Id("login_account")).SendKeys("thao09345");
    driver.FindElement(By.Id("login_pwd")).Click();
    driver.FindElement(By.Id("login_pwd")).SendKeys("HThao12345@@");
    driver.FindElement(By.LinkText("Đăng nhập")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".zidlogfrom > strong")).Text, Is.EqualTo("Thao"));
    Assert.That(driver.FindElement(By.CssSelector(".infotext > strong")).Text, Is.EqualTo("thao09345"));
    Assert.That(driver.FindElement(By.CssSelector(".selected > .zidm_itemwrapper")).Text, Is.EqualTo("Thông tin đăng nhập\\\\nQuản lý thông tin dùng để đăng nhập"));
    Assert.That(driver.FindElement(By.CssSelector("#email i")).Text, Is.EqualTo("(Chưa có thông tin)"));
    Assert.That(driver.FindElement(By.CssSelector("#phone i")).Text, Is.EqualTo("(Chưa có thông tin)"));
    Assert.That(driver.FindElement(By.CssSelector(".infotext:nth-child(3)")).Text, Is.EqualTo("********"));
  }
}
